version: '3'
services:
  itfdms-eureka:
    build:
      context: ./
      dockerfile: ./itfdms-eureka/Dockerfile
    image: itfdms-eureka
    restart: always
    ports:
      - 8761:8761
    hostname: itfdms-eureka

  itfdms-config:
    build:
      context: ./
      dockerfile: ./itfdms-config/Dockerfile
    image: itfdms-config
    hostname: itfdms-config
    restart: always
    ports:
      - 8888:8888
    links:
      - itfdms-eureka

  itfdms-gateway:
    build:
      context: ./
      dockerfile: ./itfdms-gateway/Dockerfile
    image: itfdms-gateway
    hostname: itfdms-gateway
    restart: always
    ports:
      - 9999:9999
    links:
      - itfdms-eureka
      - itfdms-config