version: '3'
services:
  itfdms-eureka:
    build:
      context: ./
      dockerfile: ./itfdms-eureka/Dockerfile
    image: itfdms-eureka
    restart: always
    ports:
      - 8761:8761
    container_name: itfdms-eureka
    hostname: itfdms-eureka
    labels:
      - 注册中心


  itfdms-config:
    build:
      context: ./
      dockerfile: ./itfdms-config/Dockerfile
    image: itfdms-config
    hostname: itfdms-config
    restart: always
    ports:
      - 8888:8888
    container_name: itfdms-config
    links:
      - itfdms-eureka
    labels:
      - 配置中心

  itfdms-gateway:
    build:
      context: ./
      dockerfile: ./itfdms-gateway/Dockerfile
    image: itfdms-gateway
    hostname: itfdms-gateway
    restart: always
    ports:
      - 9999:9999
    container_name: itfdms-gateway
    links:
      - itfdms-eureka
      - itfdms-config
    labels:
      - 网关中心


  itfdms-auth:
    build:
      context: ./
      dockerfile: ./itfdms-auth/Dockerfile
    image: itfdms-auth
    hostname: itfdms-auth
    restart: always
    ports:
      - 3000:3000
    container_name: itfdms-auth
    links:
      - itfdms-eureka
      - itfdms-config
    labels:
      - 鉴权中心