version: '3'
services:
  itfdms-eureka:
    image: itfdms-eureka
    restart: always
    ports:
      - 8761:8761

  itfdms-config:
    image: itfdms-config
    restart: always
    ports:
      - 8888:8888
    links:
      - itfdms-eureka

  itfdms-gateway:
    image: itfdms-gateway
    restart: always
    ports:
      - 9999:9999
    links:
      - itfdms-eureka
      - itfdms-config

  itfdms-auth:
    image: itfdms-auth
    restart: always
    ports:
      - 3000:3000
    links:
      - itfdms-eureka
      - itfdms-config
